import { useRef, useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Sparkles, KanbanSquare, Target, ArrowRight, Check, X, Play, Pause } from 'lucide-react'
import { cn } from '../../lib/utils'
import type { LucideIcon } from 'lucide-react'

const EASE = [0.21, 0.47, 0.32, 0.98] as const

interface SlideVideo {
  mp4: string
  webm: string
  poster: string
}

interface SlideConfig {
  id: string
  icon: LucideIcon
  color: string
  bg: string
  border: string
  glow: string
  title: string
  description: string
  video?: SlideVideo
}

// Add a `video` object to any slide once you've recorded and sent me that
// feature's clip — e.g.:
//
// import gmailSyncMp4 from '../../assets/onboarding/gmail-sync.mp4'
// import gmailSyncWebm from '../../assets/onboarding/gmail-sync.webm'
// import gmailSyncPoster from '../../assets/onboarding/gmail-sync-poster.jpg'
//
// then: video: { mp4: gmailSyncMp4, webm: gmailSyncWebm, poster: gmailSyncPoster }
//
// Slides without a `video` key fall back to the icon bubble automatically.

const SLIDES: SlideConfig[] = [
  {
    id: 'ai-sync',
    icon: Sparkles,
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/20',
    glow: 'shadow-[0_0_30px_rgba(34,211,238,0.3)]',
    title: 'AI-Powered Inbox Sync',
    description: 'Stop updating spreadsheets manually. Connect your Gmail, and our AI will instantly extract interview dates, stage changes, and meeting links from your emails.',
    // video: { mp4: gmailSyncMp4, webm: gmailSyncWebm, poster: gmailSyncPoster },
  },
  {
    id: 'kanban',
    icon: KanbanSquare,
    color: 'text-violet-400',
    bg: 'bg-violet-500/10',
    border: 'border-violet-500/20',
    glow: 'shadow-[0_0_30px_rgba(139,92,246,0.3)]',
    title: 'Visual Job Pipeline',
    description: 'Drag and drop your applications across a beautifully designed Kanban board. Always know exactly where you stand with every company at a glance.',
    // video: { mp4: kanbanDragMp4, webm: kanbanDragWebm, poster: kanbanDragPoster },
  },
  {
    id: 'insights',
    icon: Target,
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
    glow: 'shadow-[0_0_30px_rgba(16,185,129,0.3)]',
    title: 'Everything in One Place',
    description: 'Store interview notes, track salary expectations, and access one-click meeting links generated by the AI directly from your dashboard.',
    // video: { mp4: vaultUploadMp4, webm: vaultUploadWebm, poster: vaultUploadPoster },
  },
]

function DemoVideo({ sources }: { sources: SlideVideo }) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const [playing, setPlaying] = useState(true)

  const toggle = () => {
    const el = videoRef.current
    if (!el) return
    if (el.paused) {
      el.play()
      setPlaying(true)
    } else {
      el.pause()
      setPlaying(false)
    }
  }

  return (
    <div className="relative w-full overflow-hidden rounded-2xl border border-white/10 shadow-[0_0_30px_rgba(34,211,238,0.15)]">
      <span className="absolute left-3 top-3 z-10 flex items-center gap-1.5 rounded-full bg-black/50 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider text-white backdrop-blur-sm">
        <span className="h-1.5 w-1.5 rounded-full bg-cyan-400 animate-pulse" />
        Live demo
      </span>

      <video
        ref={videoRef}
        className="aspect-video w-full bg-black object-cover"
        poster={sources.poster}
        autoPlay
        loop
        muted
        playsInline
      >
        <source src={sources.webm} type="video/webm" />
        <source src={sources.mp4} type="video/mp4" />
      </video>

      <button
        onClick={toggle}
        aria-label={playing ? 'Pause demo' : 'Play demo'}
        className="absolute bottom-3 right-3 z-10 flex h-7 w-7 items-center justify-center rounded-full bg-black/50 text-white backdrop-blur-sm transition-colors hover:bg-black/70"
      >
        {playing ? <Pause size={12} /> : <Play size={12} className="ml-0.5" />}
      </button>
    </div>
  )
}

export default function WelcomeModal() {
  const [isOpen, setIsOpen] = useState(false)
  const [step, setStep] = useState(0)

  useEffect(() => {
    const hasSeen = localStorage.getItem('hasSeenWelcome')
    if (!hasSeen) {
      const timer = setTimeout(() => setIsOpen(true), 800)
      return () => clearTimeout(timer)
    }
  }, [])

  const handleComplete = () => {
    localStorage.setItem('hasSeenWelcome', 'true')
    setIsOpen(false)
  }

  const slide = SLIDES[step]

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center px-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
            onClick={handleComplete}
          />

          <motion.div
            layout
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ layout: { duration: 0.35, ease: EASE }, default: { type: 'spring', duration: 0.6, bounce: 0.3 } }}
            className="glass-raised relative w-full max-w-lg overflow-hidden rounded-3xl"
          >
            <div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/20 to-transparent" />

            <button
              onClick={handleComplete}
              className="absolute right-4 top-4 z-20 p-2 text-slate-500 transition-colors hover:text-slate-300"
            >
              <X size={18} />
            </button>

            <div className="flex flex-col items-center p-8 pb-10 text-center">

              <AnimatePresence mode="popLayout">
                {slide.video ? (
                  <motion.div
                    key={slide.id}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ duration: 0.3 }}
                    className="mb-6 w-full"
                  >
                    <DemoVideo sources={slide.video} />
                  </motion.div>
                ) : (
                  <motion.div
                    key={slide.id}
                    initial={{ scale: 0.5, opacity: 0, rotate: -20 }}
                    animate={{ scale: 1, opacity: 1, rotate: 0 }}
                    exit={{ scale: 0.5, opacity: 0, rotate: 20 }}
                    transition={{ type: 'spring', bounce: 0.5 }}
                    className={cn(
                      'mb-6 flex h-20 w-20 items-center justify-center rounded-2xl border',
                      slide.bg, slide.border, slide.glow,
                    )}
                  >
                    <slide.icon size={36} className={slide.color} />
                  </motion.div>
                )}
              </AnimatePresence>

              <AnimatePresence mode="popLayout">
                <motion.div
                  key={`text-${slide.id}`}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="min-h-[100px] space-y-3"
                >
                  <h2 className="text-2xl font-bold tracking-tight text-white">
                    {slide.title}
                  </h2>
                  <p className="mx-auto max-w-[360px] text-sm leading-relaxed text-slate-400">
                    {slide.description}
                  </p>
                </motion.div>
              </AnimatePresence>

              <div className="mt-8 flex w-full items-center justify-between">

                <div className="flex gap-2">
                  {SLIDES.map((_, i) => (
                    <div
                      key={i}
                      className={cn(
                        'h-1.5 rounded-full transition-all duration-300',
                        i === step ? 'w-6 bg-cyan-400' : 'w-1.5 bg-white/20',
                      )}
                    />
                  ))}
                </div>

                <div className="flex items-center gap-2">
                  {step > 0 && (
                    <button
                      onClick={() => setStep((s) => s - 1)}
                      className="rounded-xl px-4 py-2.5 text-sm font-medium text-slate-400 transition-colors hover:text-white"
                    >
                      Back
                    </button>
                  )}
                  <button
                    onClick={() => {
                      if (step < SLIDES.length - 1) setStep((s) => s + 1)
                      else handleComplete()
                    }}
                    className={cn(
                      'flex items-center gap-2 rounded-xl px-5 py-2.5 text-sm font-bold transition-all',
                      step === SLIDES.length - 1
                        ? 'border border-emerald-500/20 bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20'
                        : 'bg-white text-[#04060f] shadow-lg shadow-white/10 hover:bg-slate-200',
                    )}
                  >
                    {step === SLIDES.length - 1 ? (
                      <><Check size={16} /> Get Started</>
                    ) : (
                      <>Next <ArrowRight size={16} /></>
                    )}
                  </button>
                </div>
              </div>

            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}