import { useState, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Sparkles, KanbanSquare, Target, ArrowRight, Check, X } from 'lucide-react'
import { cn } from '../../lib/utils'

const EASE = [0.21, 0.47, 0.32, 0.98] as const

const SLIDES = [
  {
    id: 'ai-sync',
    icon: Sparkles,
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
    border: 'border-cyan-500/20',
    glow: 'shadow-[0_0_30px_rgba(34,211,238,0.3)]',
    title: 'AI-Powered Inbox Sync',
    description: 'Stop updating spreadsheets manually. Connect your Gmail, and our AI will instantly extract interview dates, stage changes, and meeting links from your emails.',
  },
  {
    id: 'kanban',
    icon: KanbanSquare,
    color: 'text-violet-400',
    bg: 'bg-violet-500/10',
    border: 'border-violet-500/20',
    glow: 'shadow-[0_0_30px_rgba(139,92,246,0.3)]',
    title: 'Visual Job Pipeline',
    description: 'Drag and drop your applications across a beautifully designed Kanban board. Always know exactly where you stand with every company at a glance.',
  },
  {
    id: 'insights',
    icon: Target,
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
    border: 'border-emerald-500/20',
    glow: 'shadow-[0_0_30px_rgba(16,185,129,0.3)]',
    title: 'Everything in One Place',
    description: 'Store interview notes, track salary expectations, and access one-click meeting links generated by the AI directly from your dashboard.',
  },
]

export default function WelcomeModal() {
  const [isOpen, setIsOpen] = useState(false)
  const [step, setStep] = useState(0)

  useEffect(() => {
    const hasSeen = localStorage.getItem('hasSeenWelcome')
    if (!hasSeen) {
      const timer = setTimeout(() => setIsOpen(true), 800)
      return () => clearTimeout(timer)
    }
  }, [])

  const handleComplete = () => {
    localStorage.setItem('hasSeenWelcome', 'true')
    setIsOpen(false)
  }

  const slide = SLIDES[step]

  return (
    <AnimatePresence>
      {isOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center px-4">
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="absolute inset-0 bg-black/60 backdrop-blur-sm"
            onClick={handleComplete}
          />

          <motion.div
            initial={{ opacity: 0, scale: 0.95, y: 20 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 20 }}
            transition={{ type: 'spring', duration: 0.6, bounce: 0.3 }}
            className="glass-raised relative w-full max-w-md rounded-3xl overflow-hidden"
          >
            <div className="absolute top-0 inset-x-0 h-px bg-gradient-to-r from-transparent via-white/20 to-transparent" />

            <button
              onClick={handleComplete}
              className="absolute top-4 right-4 p-2 text-slate-500 hover:text-slate-300 transition-colors z-20"
            >
              <X size={18} />
            </button>

            <div className="p-8 pb-10 flex flex-col items-center text-center">

              <AnimatePresence mode="popLayout">
                <motion.div
                  key={slide.id}
                  initial={{ scale: 0.5, opacity: 0, rotate: -20 }}
                  animate={{ scale: 1, opacity: 1, rotate: 0 }}
                  exit={{ scale: 0.5, opacity: 0, rotate: 20 }}
                  transition={{ type: 'spring', bounce: 0.5 }}
                  className={cn(
                    'w-20 h-20 rounded-2xl border flex items-center justify-center mb-6',
                    slide.bg, slide.border, slide.glow,
                  )}
                >
                  <slide.icon size={36} className={slide.color} />
                </motion.div>
              </AnimatePresence>

              <AnimatePresence mode="popLayout">
                <motion.div
                  key={`text-${slide.id}`}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  exit={{ opacity: 0, y: -10 }}
                  className="space-y-3 min-h-[120px]"
                >
                  <h2 className="text-2xl font-bold text-white tracking-tight">
                    {slide.title}
                  </h2>
                  <p className="text-sm text-slate-400 leading-relaxed max-w-[300px] mx-auto">
                    {slide.description}
                  </p>
                </motion.div>
              </AnimatePresence>

              <div className="w-full flex items-center justify-between mt-8">

                <div className="flex gap-2">
                  {SLIDES.map((_, i) => (
                    <div
                      key={i}
                      className={cn(
                        'h-1.5 rounded-full transition-all duration-300',
                        i === step ? 'w-6 bg-cyan-400' : 'w-1.5 bg-white/20',
                      )}
                    />
                  ))}
                </div>

                <button
                  onClick={() => {
                    if (step < SLIDES.length - 1) setStep(s => s + 1)
                    else handleComplete()
                  }}
                  className={cn(
                    'flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold transition-all',
                    step === SLIDES.length - 1
                      ? 'bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 border border-emerald-500/20'
                      : 'bg-white text-[#04060f] hover:bg-slate-200 shadow-lg shadow-white/10',
                  )}
                >
                  {step === SLIDES.length - 1 ? (
                    <><Check size={16} /> Get Started</>
                  ) : (
                    <>Next <ArrowRight size={16} /></>
                  )}
                </button>
              </div>

            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  )
}